name = "修改数组"
index = 3
knowledge = ['并查集']
level = 'middle'
url = 'http://lx.lanqiao.cn/problem.page?gpid=T2734'
tag = ['真题']
platform = 'lanqiao'

[[data]]
input = """
10
1 1 3 1 1 1 5 1 1 1
"""

output = """
1 2 3 4 5 6 7 8 9 10
"""

[[data]]
input = """
5
2 1 1 3 4
"""

output = """
2 1 3 4 5
"""