name = "SPFA求最短路"
index = 7
knowledge = ['SPFA']
level = 'easy'
url = 'https://www.acwing.com/activity/content/11/' 
tag = ['板子题']
platform = 'acwing'

[[data]]
input = """
3 3
1 2 5 
2 3 -3
1 3 4
"""

output = """
2
"""
