name = "合根植物"
index = 3
knowledge = ['并查集']
level = 'easy'
url = 'https://lx.lanqiao.cn/problem.page?gpid=T2850'
tag = ['真题', '板子']
platform = 'lanqiao'

[[data]]
input = """
5 4
16
2 3
1 5
5 9
4 8
7 8
9 10
10 11
11 12
10 14
12 16
14 18
17 18
15 19
19 20
9 13
13 17
"""

output = """
5
"""