name = "dijkstra"
index = 3
knowledge = ['dijkstra', "板子"]
level = 'easy'
url = 'https://www.acwing.com/problem/content/852/'
tag = ['板子']
platform = 'acwing'

[[data]]
input = """
3 3
1 2 2
2 3 1
1 3 4
"""

output = """
3
"""
